apiVersion: v1
kind: Pod
metadata:
  name: yellow
  namespace: default
spec:
  initContainers:
  - command:
    - sh
    - -c
    - sleep 20
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: warm-up-1
  containers:
  - command:
    - sleep
    - "4500"
    image: busybox
    imagePullPolicy: Always
    name: lemon
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gzh9x
      readOnly: true
  - command:
    - sleep
    - "20"
    image: busybox
    imagePullPolicy: Always
    name: gold
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gzh9x
      readOnly: true
