#replica controller template
apiVersion: 'v1'
kind: ReplicationController
metadata:
  name: recplication-controller-nginx
  labels:
    app: nginx-app
    type: front-end
spec:
  template:
    metadata:
      name: nginx-app-pod
      labels:
        app: nginx-app
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3