apt update
#This will install the kubeadm version 1.26.0
apt-get install kubeadm=1.26.0-00

#This will upgrade Kubernetes controlplane node.
kubeadm upgrade apply v1.26.0

#This will upgrade the node01 configuration.
kubeadm upgrade node

#This will update the kubelet with the version 1.26.0.
apt-get install kubelet=1.26.0-00 

#You may need to reload the daemon and restart kubelet service after it has been upgraded.
systemctl daemon-reload
!
systemctl restart kubelet